version: '3.7'
services:
  db:
    image: postgres:latest
    container_name: postgres_container
    # command: --default-authentication-plugin=mysql_native_password
    # volumes:
    #   - ./db/data:/var/lib/mysql
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: test
    restart: always

