version: "3.7"
services:
  eyeofsauron-db:
    # image: postgis/postgis:12-3.4
    # image: postgres:15.5 # homolog
    # image: postgres:10.8 # sammathnaur
    image: postgres:11.16 # eyeofsauron
    container_name: eyeofsauron-db
    restart: always
    environment:
      POSTGRES_PASSWORD: test
      PG_DATA: ~/docker/volumes/postgres/data
    volumes:
        - eyeofsauron_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  eyeofsauron_volume: